name: Publish UI

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_URL: ${{ secrets.PROD_API_URL }}
    steps:
      - name: Allow setting envs
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: install dependencies
        run: |
          npm install --global yarn
          yarn
      - name: graphql codegen
        run: |
          yarn generate
      - name: build project
        run: |
          yarn build
      - name: push assets
        run: |
          git add --force out
          git commit -am "Build"
          git subtree push --prefix out origin gh-pages
